Update anim.py
LuisMayo/objection_engine pull request #63
Opened 2022-02-23 13:54 UTC by wanghaisheng

for those language like chinese, we dont use space as a word separator

2022-02-23 16:53 UTC, LuisMayo commented
Hi.
To properly review this request I'm gonna need a bit more info about how Chinese language works.

Does Chinese have any separation marks? Anything similar to English' spaces/punctuation marks. Or is it just a continuous sequence of words without any separation?

I'm a bit curious myself to be honest.

Thanks for the request!

2022-02-23 18:18 UTC, wanghaisheng commented
you can simply take that
in chinese we do not use space to make people know these are different words not like english because words are concating of characters without space you hardly if these are one word or different words 

others are all the same

2022-02-24 10:57 UTC, LuisMayo requested changes
Hi.
Thanks a lot for the changes, but I'm afraid that this Pull Request is breaking other languages. 

Arabic for instance doesn't work at all.

French is not showing all the glyphs it could show
Your code:
![imagen](https://user-images.githubusercontent.com/20229636/155511379-7b280bc4-a383-4a4b-b354-2f532a959e99.png)
Before your code:
![imagen](https://user-images.githubusercontent.com/20229636/155511438-e6ef28c1-e37e-4a51-ac73-278d88a069a0.png)

If this issues are not fixed, this MR cannot be merged, sorry :(

2022-02-24 12:57 UTC, wanghaisheng commented
I have  no idea about french at all.
then I will leave this issue or enhance to y

2022-02-24 12:57 UTC, closed without merging